;/*FB_PKG_DELIM*/

__d("WarningFilter",["CoreWarningGK"],(function(a,b,c,d,e,f){var g=24;b=a;c=function(){return{}};function a(a){return{finalFormat:a,forceDialogImmediately:!1,monitorEvent:null,monitorListVersion:g,monitorSampleRate:1,suppressCompletely:!1,suppressDialog_LEGACY:!0}}e.exports={prepareWarning:b,getReactWarnings:c}}),null);
__d("warningBlue",["Bootloader","SiteData","WarningFilter","cr:983844"],(function(a,b,c,d,e,f,g){function a(a,b){}b=a;c=b;g["default"]=c}),98);
__d("warningBlueish",["cr:2683"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:2683")}),98);
__d("AsyncDataPreloader",["AsyncData","isEmptyObject"],(function(a,b,c,d,e,f,g){var h=new Map();a=function(){function a(a){var b=this;a=a.id;this.$1=a;this.$2=d("AsyncData").preload.call(null,this.$1);this.$2.onLoaded(function(a){c("isEmptyObject")(a)&&h.set(b.getPreloaderName(),!0)});h.set(this.getPreloaderName(),!1)}var b=a.prototype;b.getID=function(){return this.$1};b.peek=function(){return this.$2.peek()};b.onLoaded=function(a){h.set(this.getPreloaderName(),!0);this.$2.onLoaded(a);return this};b.onError=function(a){h.set(this.getPreloaderName(),!0);this.$2.onError(a);return this};b.cleanup=function(){d("AsyncData").cleanup(this.$1)};b.getContextProvider=function(){return null};b.getPreloaderName=function(){return this.$1.replace(/^adp_(.*)_[a-z0-9]+$/,"$1")};a.getUsageMap=function(){return h};return a}();g["default"]=a}),98);
__d("DGWRequestStreamDeferredClient",["Promise","nullthrows","requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";a=function(){function a(){this.$1=null}var d=a.prototype;d.createStream=function(a,b,d,e,f){this.$2();return c("nullthrows")(this.$1).then(function(c){return c.createStream(a,b,d,e,f)})};d.$2=function(){this.$1==null&&(this.$1=new(b("Promise"))(function(a){c("requireDeferred")("DGWRequestStreamClient").__setRef("DGWRequestStreamDeferredClient").onReady(function(b){a(new b())})}))};return a}();d=new a();g["default"]=d}),98);
__d("DocumentTranslationStatusContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext(!1);g["default"]=b}),98);
__d("DocumentTranslationStatusProvider.react",["DocumentTranslationStatusContext","react","uuid"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");e=d("react");var i=e.useContext,j=e.useEffect,k=e.useState;function a(a){a=a.children;var b=k(!1),d=b[0],e=b[1];j(function(){var a=document.documentElement;if(a==null)return;var b=new MutationObserver(function(){a.className.match("translated")?e(!0):e(!1)});b.observe(a,{attributeFilter:["class"],attributes:!0,characterData:!1,childList:!1});a.className.match("translated")&&e(!0);return function(){return b.disconnect()}},[]);return h.jsx(c("DocumentTranslationStatusContext").Provider,{value:d,children:a})}a.displayName=a.name+" [from "+f.id+"]";function b(){var a=i(c("DocumentTranslationStatusContext"));if(a)return c("uuid")();else return void 0}g.DocumentTranslationStatusProvider=a;g.useTranslationKeyForTextParent=b}),98);
__d("goUriOnNewWindow",["goURIOnWindow"],(function(a,b,c,d,e,f,g){"use strict";function a(a){var b=window.open("","_blank");c("goURIOnWindow")(b,a)}g["default"]=a}),98);
__d("baseTypeaheadFlattenEntries",[],(function(a,b,c,d,e,f){"use strict";function a(a){return a.flatMap(function(a){return a.type==="section"?a.entries:a})}f["default"]=a}),66);
__d("memoizeByReference",["MemoizationInstrumentation"],(function(a,b,c,d,e,f,g){"use strict";var h=typeof WeakMap==="function";function a(a,b){b===void 0&&(b=a.name||"unknown");var c=h?new WeakMap():new Map(),e=function(e){var f=d("MemoizationInstrumentation").onFunctionCall("memoizeByReference",b);if(c.has(e)){var g=c.get(e);if(g!==void 0){f&&f(!0);return g[0]}}g=a(e);c.set(e,[g]);f&&f(!1);return g};return e}g["default"]=a}),98);
__d("getGraphQLEnumSafe",["flipObject","memoizeByReference"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b){if(b==null)return null;a=h(a);return!Object.prototype.hasOwnProperty.call(a,b)?null:a[b]}var h=c("memoizeByReference")(c("flipObject"));g["default"]=a}),98);