;/*FB_PKG_DELIM*/

__d("BlueBar",["csx","CSS","DOMQuery","Style","ge"],(function(a,b,c,d,e,f,g,h){var i=document,j={};function k(a){return d("DOMQuery").scry(i,a)[0]}function l(a,b){return j[a]?j[a]:j[a]=k(b)}function a(){i=c("ge")("blueBarDOMInspector")||document,j={}}function b(){var a=n();return!a?!1:d("CSS").matchesSelector(a,"._5rmj")||c("Style").isFixed(a)}function m(){return l("bar","div._1s4v")}function e(){return l("navRoot","div._cx4")||m()}function n(){return l("maybeFixedRoot","div._26aw")}function f(){return l("maybeFixedRootLoggedOut","div._1pmx")}function h(){return l("maybeFixedRootLogin","div._53jh")}a();g.hasFixedBlueBar=b;g.getBar=m;g.getNavRoot=e;g.getMaybeFixedRoot=n;g.getLoggedOutRoot=f;g.getNewLoggedOutRoot=h}),98);
__d("LayoutAnimationBoundaryContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext(null);g["default"]=b}),98);
__d("ViewportBounds",["Arbiter","ArbiterMixin","BlueBar","ExecutionEnvironment","PageEvents","Vector","emptyFunction","removeFromArray"],(function(a,b,c,d,e,f){var g={top:[],right:[],bottom:[],left:[]};function a(a){return function(){return g[a].reduce(function(a,b){return Math.max(a,b.getSize())},0)}}function c(a,b){return function(c){return new h(a,c,b)}}var h=function(){"use strict";function a(a,c,d){d===void 0&&(d=!1),this.getSide=b("emptyFunction").thatReturns(a),this.getSize=function(){return typeof c==="function"?c():c},this.isPersistent=b("emptyFunction").thatReturns(d),g[a].push(this),i.inform("change")}var c=a.prototype;c.remove=function(){b("removeFromArray")(g[this.getSide()],this),i.inform("change")};return a}();b("Arbiter").subscribe(b("PageEvents").AJAXPIPE_ONUNLOAD,function(){["top","right","bottom","left"].forEach(function(a){a=g[a];for(var b=a.length-1;b>=0;b--){var c=a[b];c.isPersistent()||c.remove()}})});var i=babelHelpers["extends"]({},b("ArbiterMixin"),{getTop:a("top"),getRight:a("right"),getBottom:a("bottom"),getLeft:a("left"),getElementPosition:function(a){a=b("Vector").getElementPosition(a);a.y-=i.getTop();return a},addTop:c("top"),addRight:c("right"),addBottom:c("bottom"),addLeft:c("left"),addPersistentTop:c("top",!0),addPersistentRight:c("right",!0),addPersistentBottom:c("bottom",!0),addPersistentLeft:c("left",!0)});i.addPersistentTop(function(){if(b("ExecutionEnvironment").canUseDOM&&b("BlueBar").hasFixedBlueBar()){var a=b("BlueBar").getMaybeFixedRoot();return a?a.offsetHeight:0}return 0});e.exports=i}),null);
__d("isAsyncScrollQuery",["UserAgent"],(function(a,b,c,d,e,f,g){var h=null;function a(){h===null&&(h=c("UserAgent").isPlatform("Mac OS X >= 10.8")&&c("UserAgent").isBrowser("Safari >= 6.0"));return h}g["default"]=a}),98);
__d("testID",["gkx"],(function(a,b,c,d,e,f,g){"use strict";var h=c("gkx")("1070695");function a(a){return h&&a!=null?{"data-testid":a}:void 0}g["default"]=a}),98);
__d("ReactDOMComet",["cr:1108857","cr:1294159","gkx","qex"],(function(a,b,c,d,e,f,g){function a(a,d){return b("cr:1294159").createRoot(a,babelHelpers["extends"]({},d,{unstable_concurrentUpdatesByDefault:c("qex")._("723")?!1:(a=d==null?void 0:d.unstable_concurrentUpdatesByDefault)!=null?a:!1}))}function d(a,d,e){return b("cr:1294159").hydrateRoot(a,d,babelHelpers["extends"]({onRecoverableError:function(a){if(a!=null&&typeof a.message==="string"){var b=a.message;if(b.indexOf("The server could not finish this Suspense boundary")!==-1||b.indexOf("Minified React error #419;")!==-1||b.indexOf("This Suspense boundary received an update")!==-1||b.indexOf("Minified React error #421;")!==-1)return}typeof reportError==="function"&&reportError(a)}},e,{unstable_concurrentUpdatesByDefault:c("qex")._("723")?!1:(a=e==null?void 0:e.unstable_concurrentUpdatesByDefault)!=null?a:!1}))}e=c("gkx")("1465")?b("cr:1294159").flushSync:b("cr:1294159").unstable_flushControlled;g.createPortal=b("cr:1294159").createPortal;g.unstable_batchedUpdates=b("cr:1294159").unstable_batchedUpdates;g.flushSync=b("cr:1294159").flushSync;g.createRoot=a;g.hydrateRoot=d;g.unstable_flushControlled=e;g.unstable_createEventHandle=b("cr:1294159").unstable_createEventHandle;g.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED=b("cr:1294159").__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;g.version=b("cr:1294159").version}),98);
__d("useCometPreloader",["cr:1651548"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:1651548")}),98);
__d("useUnsafeRef_DEPRECATED",["react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useMemo;function a(a){return h(function(){return{current:a}},[])}g["default"]=a}),98);