;/*FB_PKG_DELIM*/

__d("MessengerWellbeingRestrictFailedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("474");b=d("FalcoLoggerInternal").create("messenger_wellbeing_restrict_failed",a);e=b;g["default"]=e}),98);
__d("MessengerWellbeingRestrictFailedFalcoEvent.bs",["MessengerWellbeingRestrictFailedFalcoEvent"],(function(a,b,c,d,e,f){"use strict";function a(a){b("MessengerWellbeingRestrictFailedFalcoEvent").log(a)}function c(a){b("MessengerWellbeingRestrictFailedFalcoEvent").logAsync(a)}function d(a){b("MessengerWellbeingRestrictFailedFalcoEvent").logImmediately(a)}function e(a){b("MessengerWellbeingRestrictFailedFalcoEvent").logCritical(a)}f.log=a;f.logAsync=c;f.logImmediately=d;f.logCritical=e}),null);
__d("MessengerWellbeingRestrictSucceededFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("480");b=d("FalcoLoggerInternal").create("messenger_wellbeing_restrict_succeeded",a);e=b;g["default"]=e}),98);
__d("MessengerWellbeingRestrictSucceededFalcoEvent.bs",["MessengerWellbeingRestrictSucceededFalcoEvent"],(function(a,b,c,d,e,f){"use strict";function a(a){b("MessengerWellbeingRestrictSucceededFalcoEvent").log(a)}function c(a){b("MessengerWellbeingRestrictSucceededFalcoEvent").logAsync(a)}function d(a){b("MessengerWellbeingRestrictSucceededFalcoEvent").logImmediately(a)}function e(a){b("MessengerWellbeingRestrictSucceededFalcoEvent").logCritical(a)}f.log=a;f.logAsync=c;f.logImmediately=d;f.logCritical=e}),null);
__d("MessengerWellbeingRestrictTappedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("481");b=d("FalcoLoggerInternal").create("messenger_wellbeing_restrict_tapped",a);e=b;g["default"]=e}),98);
__d("MessengerWellbeingRestrictTappedFalcoEvent.bs",["MessengerWellbeingRestrictTappedFalcoEvent"],(function(a,b,c,d,e,f){"use strict";function a(a){b("MessengerWellbeingRestrictTappedFalcoEvent").log(a)}function c(a){b("MessengerWellbeingRestrictTappedFalcoEvent").logAsync(a)}function d(a){b("MessengerWellbeingRestrictTappedFalcoEvent").logImmediately(a)}function e(a){b("MessengerWellbeingRestrictTappedFalcoEvent").logCritical(a)}f.log=a;f.logAsync=c;f.logImmediately=d;f.logCritical=e}),null);
__d("MessengerWellbeingUnrestrictFailedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("482");b=d("FalcoLoggerInternal").create("messenger_wellbeing_unrestrict_failed",a);e=b;g["default"]=e}),98);
__d("MessengerWellbeingUnrestrictFailedFalcoEvent.bs",["MessengerWellbeingUnrestrictFailedFalcoEvent"],(function(a,b,c,d,e,f){"use strict";function a(a){b("MessengerWellbeingUnrestrictFailedFalcoEvent").log(a)}function c(a){b("MessengerWellbeingUnrestrictFailedFalcoEvent").logAsync(a)}function d(a){b("MessengerWellbeingUnrestrictFailedFalcoEvent").logImmediately(a)}function e(a){b("MessengerWellbeingUnrestrictFailedFalcoEvent").logCritical(a)}f.log=a;f.logAsync=c;f.logImmediately=d;f.logCritical=e}),null);
__d("MessengerWellbeingUnrestrictSucceededFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("483");b=d("FalcoLoggerInternal").create("messenger_wellbeing_unrestrict_succeeded",a);e=b;g["default"]=e}),98);
__d("MessengerWellbeingUnrestrictSucceededFalcoEvent.bs",["MessengerWellbeingUnrestrictSucceededFalcoEvent"],(function(a,b,c,d,e,f){"use strict";function a(a){b("MessengerWellbeingUnrestrictSucceededFalcoEvent").log(a)}function c(a){b("MessengerWellbeingUnrestrictSucceededFalcoEvent").logAsync(a)}function d(a){b("MessengerWellbeingUnrestrictSucceededFalcoEvent").logImmediately(a)}function e(a){b("MessengerWellbeingUnrestrictSucceededFalcoEvent").logCritical(a)}f.log=a;f.logAsync=c;f.logImmediately=d;f.logCritical=e}),null);
__d("MessengerWellbeingUnrestrictTappedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("484");b=d("FalcoLoggerInternal").create("messenger_wellbeing_unrestrict_tapped",a);e=b;g["default"]=e}),98);
__d("MessengerWellbeingUnrestrictTappedFalcoEvent.bs",["MessengerWellbeingUnrestrictTappedFalcoEvent"],(function(a,b,c,d,e,f){"use strict";function a(a){b("MessengerWellbeingUnrestrictTappedFalcoEvent").log(a)}function c(a){b("MessengerWellbeingUnrestrictTappedFalcoEvent").logAsync(a)}function d(a){b("MessengerWellbeingUnrestrictTappedFalcoEvent").logImmediately(a)}function e(a){b("MessengerWellbeingUnrestrictTappedFalcoEvent").logCritical(a)}f.log=a;f.logAsync=c;f.logImmediately=d;f.logCritical=e}),null);